include: package:lint/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    # ignore warnings in files from generators
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/injection.config.dart'
    - '**/generated/*'
    - '**/mocks.mocks.dart'
  errors:
    avoid_classes_with_only_static_members: ignore
    # TODO 2) check the NNBD ignores are valid
    invalid_annotation_target: ignore
    avoid_dynamic_calls: ignore

linter:
  rules:
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_pub_dependencies: false
    always_use_package_imports: false
